export const tagMap = {
  "🚧": ["WIP", "draft"],
  "💻": [
    "C",
    "Go",
    "Rust",
    "TypeScript",
    "Python",
    "Unity",
    "Ruby",
    "C#",
    "Vue",
    "React",
    "Kotlin",
    "Swift",
  ],
  "🏷️": [
    "Bot",
    "OS",
    "コンパイラ",
    "自作言語インタプリタ",
    "ポートフォリオ",
    "低レイヤー",
    "ツール",
    "アプリ",
    "webサービス",
    "ブログ",
    "Webアプリ",
  ],
  "📚": ["読書", "授業", "課題"],
  "🚰": ["Spigotプラグイン"],
  "🎨": ["アイコン", "MineCraft", "Youtube"],
  "🖐️": ["ipu"],
  "🤔": ["ポエム"],
  "✔": ["じぶんリリースノート", "週報", "月報"],
}
