name: GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  YARN_CACHE_FOLDER: .cache/yarn
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.REPO_PAT }}
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ${YARN_CACHE_FOLDER}
          key: ${{ runner.os }}-yarn-cache-v1
      - run: yarn install --frozen-lockfile
      - run: yarn build
        env:
          GOOGLE_ANALYTICS_TRACKING_ID: ${{ secrets.GOOGLE_ANALYTICS_TRACKING_ID }}
          LOCAL_VAULT_PATH: ${{ secrets.LOCAL_VAULT_PATH }}
      - name: Deploy
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=./public --prod